steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --cache=true
      - --cache-ttl=1440h
      - --snapshotMode=redo

tags:
  - asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${SERVICE_NAME}:latest
