steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:latest
      - --cache=true
      - --cache-ttl=1440h
      - --snapshotMode=redo
      - --use-new-run

substitutions:
  _SERVICE_NAME: NULL_SERVICE_NAME
