name: "setup-env"
description: "set vars by branch name"
runs:
  using: "composite"
  steps:
    - name: Change ENV if not main
      if: github.ref != 'refs/heads/main'
      shell: bash
      run: |
        echo "SERVICE_NAME=$SERVICE_NAME-$GITHUB_REF_NAME" >> $GITHUB_ENV
        echo "HOST=market-$GITHUB_REF_NAME.moonshine.tw" >> $GITHUB_ENV
