const deftag = {
    common: {
        text_logo: 'Moonshine Market',
        text_menu_store: '商店',
        text_menu_about: '關於',
        text_menu_tutorial: '文件',
        btn_submit: '確認送出',
        btn_show_more: '顯示更多',
    },
    header: {
        text_cart_title: '購物車品項',
        text_go_to_checkout: '前往結帳',
        text_empty_cart: '購物車是空的...',
    },
    memberSign: {
        text_signin: '登入',
        text_register: '註冊',
        text_forgot_password: '忘記密碼',
        text_confirm_password: '確認密碼',
        btn_return_to_signin: '回到登入頁',
        text_nick_name: '暱稱',
        text_real_name: '姓名',
        text_account_with_email: '電子信箱 / 帳號',
        text_enter_password: '輸入密碼',
        text_aggree_privacy: '我同意服務條款及隱私權條款',
        text_signin_title: '帳號登入',
        text_account: '帳號',
        text_password: '密碼',
        text_enter_register_email: '請輸入註冊時的電子信箱',
        btn_get_reset_password_link: '取得重設密碼連結',
        text_reset_password: '重設密碼',
        text_new_password: '輸入新密碼',
        text_new_password_success: '你的登入密碼已設定成功',
        text_signin_with_google: '使用 Google 帳號登入',
        text_email_sent: '已成功發送至你輸入的電子信箱',
    },
    home: {
        page_title: '首頁',
        section_title_new_arrival: '新品',
        section_title_tutorial: '教學文件',
    },
    product: {
        page_title: '商店',
        select_label: '標籤篩選',
        product_category: '商品分類',
        detail_section_title1: '商品內容展示圖',
        detail_section_title2: '你可能會喜歡的',
        button_add_to_card: '加到購物車',
        notice_message: '格式僅為第一次選擇，購買後，仍可以在使用者後台下載其他格式檔案',
        detail_option_format: '軟體格式',
        detail_option_renderer: '算圖引擎',
    },
    member: {
        my_account: '我的帳號',
        text_member_center: '會員中心',
        text_logout: '登出',
    },
    cart: {
        text_order_title: '商品購買',
        btn_confirm_order: '送出訂單',
        section_title: '商品確認',
        text_title_format: '軟體格式：',
        text_title_render: '算圖引擎：',
        text_notice: '送出訂單後將會離開此頁面。'
    },
    about: {
        page_title: '關於我們',
        support_model: '套模型',
        support_software: '種 3D 軟體格式',
        support_render: '個以上算圖引擎支援',
    },
    tutorial: {
        page_title: '網站使用文件',
    },
    error: {
        error_required: '此欄位為必填',
        error_pattern: '格式有誤',
        error_password_different: '兩次輸入的密碼可能不同',
        error_password_at_least_eight: '至少 8 碼',
    },
};

export default deftag;
