const deftag = {
    common: {
        text_logo: 'Moonshine Market',
        text_menu_store: '商店',
        text_menu_about: '關於',
        text_menu_tutorial: '文件',
        btn_submit: '確認送出',
        btn_show_more: '顯示更多',
        text_item_unit: '項',
        btn_lightbox_cancel: '取消',
        btn_lightbox_submit: '確認',
        text_verify_not_robot: '按此驗證我不是機器人',
    },
    header: {
        text_cart_title: '購物車品項',
        text_go_to_checkout: '前往結帳',
        text_empty_cart: '購物車是空的...',
    },
    footer: {
        text_privacy_link: '隱私權政策',
        text_custom_service: '客服信箱資訊',
    },
    memberSign: {
        text_signin: '登入',
        text_register: '註冊',
        text_forgot_password: '忘記密碼',
        text_confirm_password: '確認密碼',
        btn_return_to_signin: '回到登入頁',
        text_nickname: '暱稱',
        text_real_name: '姓名',
        text_account_with_email: '電子信箱 / 帳號',
        text_enter_password: '輸入密碼',
        text_agree_privacy: '我同意服務條款及隱私權條款',
        text_signin_title: '帳號登入',
        text_account: '帳號',
        text_password: '密碼',
        text_enter_register_email: '請輸入註冊時的電子信箱',
        btn_get_reset_password_link: '取得重設密碼連結',
        text_reset_password: '重設密碼',
        text_new_password: '輸入新密碼',
        text_new_password_success: '你的登入密碼已設定成功',
        text_signin_with_google: '使用 Google 帳號登入',
        text_email_sent: '已成功發送至你輸入的電子信箱',
        text_register_success_title: '註冊成功',
        text_register_success_message: '請至信箱收取驗證信並啟用帳號。',
        text_active_account_title: '帳號啟用',
        text_active_account_message: '帳號已啟用！',
    },
    home: {
        page_title: '首頁',
        section_title_new_arrival: '新品',
        section_title_tutorial: '教學文件',
    },
    product: {
        page_title: '商店',
        text_filter_no_product: '找不到商品',
        select_label: '標籤篩選',
        product_category: '商品分類',
        detail_section_title1: '商品內容展示圖',
        detail_section_title2: '你可能會喜歡的',
        button_add_to_card: '加到購物車',
        notice_message: '購買後，可以在我的模型庫下載其他檔案格式',
        detail_format_and_render: '軟體格式與算圖引擎',
        detail_option_format: '軟體格式',
        detail_option_renderer: '算圖引擎',
        text_file_size: '檔案大小',
        text_download: '下載',
        text_model_sum: '模型數量',
        text_per_image_size: '貼圖尺寸',
    },
    member: {
        my_account: '我的帳號',
        text_member_center: '會員中心',
        text_logout: '登出',
        text_my_product: '我的模型庫',
        text_order_record: '訂單記錄',
        text_account_edit: '修改會員資料',
        btn_save: '儲存',
        text_old_password: '輸入舊密碼',
        text_change_password: '修改密碼',
        text_change_password_success: '密碼修改成功，將回到會員中心。',
        btn_return_to_account: '回到會員中心',
        text_mobile_download_notice: '行動版網頁不顯示下載功能，請至 PC 版網頁下載。',
    },
    orderRecord: {
        text_status_unpaid: '等待付款',
        text_status_success: '交易成功',
        text_status_fail: '交易失敗',
        text_status_cancel: '取消交易',
        text_order_number: '訂單編號',
        text_order_create_at: '訂單成立日期',
        text_order_paid_at: '付款日期',
        text_order_status: '訂單狀態',
        text_order_quantity: '數量',
        text_order_total_price: '總額',
        text_order_payment: '付款方式',
        text_order_invoice: '發票編號',
        text_payment_CREDIT: '信用卡',
        text_payment_VACC: 'ATM 轉帳',
        text_order_detail_title: '訂單明細',
    },
    cart: {
        text_order_title: '商品購買',
        btn_confirm_order: '送出訂單',
        section_title: '商品確認',
        text_notice: '送出訂單後將會離開此頁面。',
        text_empty_cart: '購物車是空的...',
    },
    about: {
        page_title: '關於我們',
        support_model: '套模型',
        support_software: '種 3D 軟體格式',
        support_render: '個以上算圖引擎支援',
    },
    tutorial: {
        page_title: '網站使用文件',
    },
    paymentResult: {
        page_title: '付款結果',
        text_message: '資訊將在3分鐘後更新',
        text_direct_to_order_detail: '查看訂單詳細',
    },
    privacy: {
        page_title: '會員條款與隱私權政策',
    },
    error: {
        error_required: '此欄位為必填',
        error_pattern: '格式有誤',
        error_password_different: '兩次輸入的密碼可能不同',
        error_password_at_least_eight: '至少 8 碼',
    },
};

export default deftag;
