const deftag = {
    common: {
        og_title: '模型平台',
        og_description: '模型,3D,素材',
        text_logo: 'Moonshine Market',
        text_logout: '登出',
        menu_store: '商店',
        menu_about: '關於',
        menu_tutorial: '文件',
        btn_submit: '確認送出',
        btn_show_more: '顯示更多',
        btn_cancel: '取消',
        btn_confirm: '確認',
        btn_verify: '驗證',
        currency_tw: 'NT',
        currency_en: 'USD',
        lang_zh: '繁體中文',
        lang_en: 'English',
        lang_cn: '简体中文',
        lang_jp: '日文',
    },
    header: {
        cart_box_title: '購物車品項',
        cart_go_to_checkout: '前往結帳',
    },
    footer: {
        text_privacy: '隱私權政策',
        text_custom_service: '客服信箱',
    },

    // Betty: 與 header cart 接近
    cart: {
        cart_order_title: '商品購買',
        btn_confirm_order: '送出訂單',
        cart_section_title: '商品確認',
        cart_text_notice: '送出訂單後將會離開此頁面。',
        cart_text_empty: '購物車是空的...',
    },
    memberSign: {
        text_signin: '登入',
        text_signin_title: '帳號登入',
        text_account: '電子信箱',
        text_password: '密碼',
        text_signin_with_google: '使用 Google 帳號登入',
        text_forgot_password: '忘記密碼',
        text_register: '註冊',
        text_nickname: '暱稱',
        text_real_name: '姓名',
        text_enter_password: '輸入密碼',
        text_confirm_password: '確認密碼',
        text_agree_privacy: '我同意服務條款及隱私權條款',
        btn_return_to_signin: '回到登入頁',
        text_enter_register_email: '請輸入註冊時的電子信箱',
        btn_get_reset_password_link: '取得重設密碼連結',
        text_reset_password: '重設密碼',
        text_new_password: '輸入新密碼',
        text_new_password_success: '你的登入密碼已設定成功',
        text_email_sent: '已成功發送至你輸入的電子信箱',
        text_register_success_message: '請至信箱收取驗證信並啟用帳號。',
        text_active_account_title: '帳號啟用',
        text_active_account_message: '帳號已啟用！',
    },
    home: {
        home_title: '首頁',
        home_section_title01: '最新上架',
        home_section_title02: '教學文件',
    },
    product: {
        product_no_data: '找不到商品',
        product_select_label: '標籤篩選',
        product_detail_section_title01: '商品內容展示圖',
        product_detail_section_title02: '你可能會喜歡的',
        btn_add_to_cart: '加到購物車',
        product_detail_notice_message: '購買後，可以在我的模型庫下載其他檔案格式',
        product_detail_format_and_render: '軟體格式與算圖引擎',
        product_format: '軟體格式',
        product_render: '算圖引擎',
        product_file_size: '檔案大小',
        product_download: '下載',
        product_model_sum: '模型數量',
        product_per_image_size: '貼圖尺寸',
    },
    member: {
        member_my_account: '我的帳號',
        member_account_center: '會員中心',
        member_my_product: '我的模型庫',
        member_account_update: '修改會員資料',
        member_old_password: '輸入舊密碼',
        member_change_password: '修改密碼',
        member_change_password_success: '密碼修改成功，將回到會員中心。',
        member_mobile_download_notice: '行動版網頁不顯示下載功能，請至 PC 版網頁下載。',
        btn_saved: '儲存',
        text_return_to_account: '回到會員中心',
    },
    orderRecord: {
        order_text_order_record: '訂單記錄',
        order_status_unpaid: '等待付款',
        order_status_success: '交易成功',
        order_status_fail: '交易失敗',
        order_status_cancel: '取消交易',
        order_text_order_number: '訂單編號',
        order_text_create_at: '訂單成立日期',
        order_text_paid_at: '付款日期',
        order_text_status: '訂單狀態',
        order_text_quantity: '數量',
        order_text_total_price: '總額',
        order_text_payment: '付款方式',
        order_text_invoice: '發票編號',
        order_payment_CREDIT: '信用卡',
        order_payment_VACC: 'ATM 轉帳',
        order_detail: '訂單明細',
        order_success: '購買成功',
    },
    about: {
        about_title: '關於我們',
        about_support_model: '套模型',
        about_support_software: '種 3D 軟體格式',
        about_support_render: '個以上算圖引擎支援',
    },
    tutorial: {
        tutorial_title: '教學文件',
    },
    privacy: {
        privacy_title: '會員條款與隱私權政策',
    },
    error: {
        error_required: '此欄位為必填',
        error_pattern: '格式有誤',
        error_password_different: '兩次輸入的密碼可能不同',
        error_password_at_least_eight: '至少 8 碼',
    },
};

export default deftag;
