name: Entry

on:
  push:
    branches:
      - main
      - release
      - dev

jobs:
  apply-env:
    name: Apply env
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'no-action')"
    outputs:
      env_var: ${{ steps.var.outputs.env_var }}
    steps:
      - id: var
        run: | 
          if [ $GITHUB_REF_NAME == 'main' ]; then
              echo "::set-output name=env_var::master"
          else
              echo "::set-output name=env_var::$GITHUB_REF_NAME"
          fi

  call-workflow:
    needs:
      - apply-env
    name: Call workflow
    secrets: inherit
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      env_input: ${{ needs.apply-env.outputs.env_var }}
